[supervisord]
user=root
nodaemon=true
logfile=/app/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:postgres]
command=su postgres -c "/usr/lib/postgresql/16/bin/postgres -D %(ENV_DATA_DIR)s/postgres -c listen_addresses=127.0.0.1 -c port=5432"
autostart=true
autorestart=true
stdout_logfile=/app/logs/postgres.log
stderr_logfile=/app/logs/postgres.err.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=2
priority=1

[program:splitpro]
directory=/app
command=node server.js
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PORT="3000",HOSTNAME="0.0.0.0"
priority=10
